# Generated by Django 3.0.11 on 2020-11-04 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Promo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('promo_type', models.CharField(choices=[('CV', 'Constant Value'), ('P', 'Percent')], max_length=2, null=True, verbose_name='Promo Type')),
                ('promo_code', models.CharField(max_length=10, null=True, unique=True, verbose_name='Promo Code')),
                ('creation_time', models.DateField(auto_now_add=True, verbose_name='Created At')),
                ('start_time', models.DateField(verbose_name='Start Time')),
                ('end_time', models.DateField(verbose_name='End Time')),
                ('promo_amount', models.IntegerField(verbose_name='Promo Amount')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
            ],
            options={
                'verbose_name': 'Promo',
                'verbose_name_plural': 'Promos',
                'db_table': 'promos',
            },
        ),
    ]
